-- Добавляем дополнительные поля для профиля пользователя
ALTER TABLE users ADD COLUMN IF NOT EXISTS bio TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS gender VARCHAR(20);
ALTER TABLE users ADD COLUMN IF NOT EXISTS age_from INTEGER;
ALTER TABLE users ADD COLUMN IF NOT EXISTS age_to INTEGER;
ALTER TABLE users ADD COLUMN IF NOT EXISTS city VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS district VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS height INTEGER;
ALTER TABLE users ADD COLUMN IF NOT EXISTS body_type VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS marital_status VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS children VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS financial_status VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS has_car BOOLEAN;
ALTER TABLE users ADD COLUMN IF NOT EXISTS has_housing BOOLEAN;
ALTER TABLE users ADD COLUMN IF NOT EXISTS dating_goal TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS interests TEXT[];
ALTER TABLE users ADD COLUMN IF NOT EXISTS profession VARCHAR(100);